### ISSUE TITLE
Capture ruby install version

### ISSUE THREAD

**Issue by thapakazi** [innohub-ansible/ruby-install#1]
Please fix this :book too, Thanks :octocat: 
https://github.com/innohub-ansible/ruby-install/blob/master/tasks/main.yml#L30
![fixed_as_in_chruby](http://i.imgur.com/obREsB8.png)

**Comment by dukz** [comment]
I'm not sure what you mean. :)

**Comment by thapakazi** [comment]
I mean this [line](https://github.com/innohub-ansible/ruby-install/blob/master/tasks/main.yml#L31) need modificating like as in above image, ruby-install is not found in path, so it outputs blank.

**Comment by dukz** [comment]
Ah. Alright. :) Thanks. Strange that it didn't blow up.

**Comment by dukz** [comment]
@zerOnepal I just realized that this is ruby-install, and it's installed in /usr/local/bin/ directory. So there is acutally no need to source /etc/profile. 

The only time to do source /etc/profile is when loading ruby using chruby.

There might be a different underlying reason for your system to not find the ruby-install executable.
